language: python

notifications:
  email: false
  
python:
  - "2.7"
  
install:
  - pip install -r requirements/edx/paver.txt
  - pip install python-memcached
  - pip install scipy==0.11.0

script:
  - paver test
